import json, shutil, glob, os
S = json.load(open("/tmp/rec/session.json")); C = json.load(open("/tmp/demo/conversation.json"))
OUT = "/home/user/Voice-to-voice-model-training/demo/video"
pub = f"{OUT}/public"
FPS, DUR = 30, 60.0
A0, A1 = 2.4, 60.4                       # main segment of the recording (continuous)
end_click = next(c for c in S["clicks"] if c["label"] == "End call")
C0 = end_click["t"] - 0.2; C1 = C0 + 1.6  # end-call segment
def out_t(rec):
    if A0 <= rec <= A1: return round(rec - A0, 3)
    if C0 <= rec <= C1: return round((A1 - A0) + rec - C0, 3)
    return None
ev = S["events"]; get = lambda typ, turn: next(e["t"] for e in ev if e["type"] == typ and e.get("turn") == turn)
segments = [{"src": "recording.webm", "from_s": A0, "to_s": A1, "at_s": 0.0},
            {"src": "recording.webm", "from_s": round(C0, 3), "to_s": round(C1, 3), "at_s": round(A1 - A0, 3)}]
audio = []
for i, t in enumerate(C["turns"]):
    audio.append({"src": f"audio/guest_{i}.wav", "at_s": out_t(get("guest_start", i)), "duration_s": t["guest_seconds"], "who": "guest", "text": t["guest_text"]})
    audio.append({"src": f"audio/bot_{i}.wav", "at_s": out_t(get("bot_start", i)), "duration_s": t["bot_seconds"], "who": "bot", "text": " ".join(t["assistant"])})
turn_scene = [
    ("Guest: “Hi! Who are you?”", "The guest just talks. Our model hears the speech directly and answers in its own voice."),
    ("Tool call → order_product · 2 towels · Order #8001", "It understands the request, calls the hotel's ordering tool, then confirms out loud."),
    ("Tool call → create_issue · maintenance ticket #501", "Problems become maintenance tickets automatically."),
    ("Lookup → get_property_information · breakfast", "Hotel facts come from the property-info tool, never made up."),
    ("Answer from the booking → room 517", "Questions about the stay are answered from the guest's reservation."),
]
scenes = [{"id": "intro", "start_s": 0.0, "end_s": out_t(get("guest_start", 0)), "caption": "Our own speech-to-speech LLM",
           "subtitle": "Hotel voice concierge · 1.3B parameters · tool calling",
           "narration": "This is our hotel voice concierge, a speech-to-speech model we trained ourselves.",
           "screenshot": "shots/01_landing.png"}]
shots = {0: "shots/04_greeting.png", 1: "shots/06_tool_details.png", 2: "shots/07_issue.png", 3: "shots/08_breakfast.png", 4: "shots/09_room.png"}
for i, (cap, nar) in enumerate(turn_scene):
    start = out_t(get("guest_start", i)); end = out_t(get("guest_start", i + 1)) if i + 1 < len(turn_scene) else out_t(get("bot_end", i)) + 0.3
    scenes.append({"id": f"turn{i+1}", "start_s": start, "end_s": end, "caption": cap, "narration": nar, "screenshot": shots[i],
                   "guest_audio": f"audio/guest_{i}.wav", "bot_audio": f"audio/bot_{i}.wav",
                   "latency_s": C["latency_ms"][i] / 1000, "tools": C["turns"][i]["tool_calls"]})
scenes.append({"id": "outro", "start_s": scenes[-1]["end_s"], "end_s": DUR, "caption": "≈1 s to first audio · runs on one GPU",
               "subtitle": "99.7% tool accuracy on our clean hotel test set", "narration": "Fast, accurate, and it runs on our own servers.",
               "screenshot": "shots/10_end.png"})
highlights = [{"label": c["label"], "selector": c["selector"], "at_s": out_t(c["t"]), "box": c["box"]} for c in S["clicks"] if out_t(c["t"]) is not None]
sb = {"title": "Voice Concierge demo", "fps": FPS, "width": 1920, "height": 1080, "duration_s": DUR,
      "note": "Guest voice: Kokoro am_michael. Bot voice and every reply/tool call: generated by our model (Parakeet → adapter v3 → thinker v2 → talker v2 → Mimi). Latency figures: Kaggle T4 live test.",
      "segments": segments, "audio": audio, "scenes": scenes, "highlights": highlights}
json.dump(sb, open(f"{OUT}/storyboard.json", "w"), indent=1)
json.dump(sb, open(f"{pub}/storyboard.json", "w"), indent=1)
shutil.copy(S["video"], f"{pub}/recording.webm")
shutil.rmtree(f"{pub}/audio", ignore_errors=True); shutil.copytree("/tmp/demo/audio", f"{pub}/audio")
shutil.rmtree(f"{pub}/shots", ignore_errors=True); shutil.copytree("/tmp/rec/shots", f"{pub}/shots")
print(json.dumps([(s["id"], s["start_s"], s["end_s"]) for s in scenes])); print(highlights); print([(a["src"], a["at_s"]) for a in audio])
